/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh JWT access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate refresh token */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset code */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset with code */
        post: operations["confirmPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        /** Delete user account and all data */
        delete: operations["deleteCurrentUser"];
        options?: never;
        head?: never;
        /** Update user profile */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/users/me/tokens/{platform}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configure platform API token */
        put: operations["configurePlatformToken"];
        post?: never;
        /** Remove platform API token */
        delete: operations["removePlatformToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/tokens/{platform}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-verify platform token validity */
        post: operations["verifyPlatformToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export all user data (GDPR) */
        get: operations["exportUserData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enrolled courses */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get course detail with assessment weights */
        get: operations["getCourseDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get grade list for a course */
        get: operations["getCourseGrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get course materials (Canvas modules + Ed lessons) */
        get: operations["getCourseMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/discussions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get high-value discussion threads for a course */
        get: operations["getCourseDiscussions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/deadlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deadlines for a single course */
        get: operations["getCourseDeadlines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/outline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get parsed unit outline for a course */
        get: operations["getCourseOutline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current GPA/WAM report */
        get: operations["getGpaReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpa/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What-if GPA prediction */
        post: operations["predictGpa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpa/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate path to target GPA */
        post: operations["calculateGpaPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deadlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unified deadline timeline across all courses */
        get: operations["listDeadlines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deadlines/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deadlines within the next 7 days */
        get: operations["getUpcomingDeadlines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest daily academic digest */
        get: operations["getLatestDigest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get digest history with pagination */
        get: operations["getDigestHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get risk alerts */
        get: operations["getAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user notifications */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually trigger data synchronization */
        post: operations["triggerSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current sync status */
        get: operations["getSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text search across materials and discussions */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (no auth required) */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timetable/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List timetable sessions, optionally filtered by teaching week */
        get: operations["getTimetableSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timetable/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all semester weeks with teaching week mapping */
        get: operations["getSemesterWeeks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResponseMeta: {
            /** Format: uuid */
            request_id: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorResponse: {
            error: {
                code: components["schemas"]["ErrorCode"];
                message: string;
            };
        };
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "AUTH_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "TOKEN_INVALID" | "RATE_LIMITED" | "UPSTREAM_ERROR" | "INTERNAL_ERROR";
        CursorPagination: {
            next_cursor: string | null;
            has_more: boolean;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            gpa_target: number | null;
            /** @enum {string} */
            gpa_scale: "wam" | "gpa_4" | "gpa_7";
            tokens: {
                canvas: components["schemas"]["TokenStatus"];
                ed: components["schemas"]["TokenStatus"];
            };
            /** Format: date-time */
            created_at: string;
        };
        TokenStatus: {
            /** @enum {string} */
            status: "active" | "invalid" | "not_configured";
            /** Format: date-time */
            last_verified_at: string | null;
        };
        Course: {
            /** @example crs_abc123 */
            id: string;
            /** @example Systems Programming */
            name: string;
            /** @example COMP2017 */
            code: string;
            /** @example 2026-S1 */
            semester: string;
            /** @example 6 */
            credit_points: number;
            canvas_course_id?: string;
            ed_course_id?: string;
            /** @example 82.5 */
            current_mark?: number | null;
            /** @example D */
            grade_letter?: string | null;
            /** @example 0.4 */
            completed_weight?: number;
            has_unit_outline?: boolean;
            /** Format: date-time */
            last_sync_at?: string;
        };
        CourseDetail: components["schemas"]["Course"] & {
            assessment_weights: components["schemas"]["AssessmentWeight"][];
            /** @enum {string} */
            weight_source: "unit_outline" | "canvas_assignment_groups";
        };
        AssessmentWeight: {
            name: string;
            weight: number;
            score: number | null;
            max_score: number;
            /** @enum {string} */
            status: "graded" | "upcoming" | "submitted";
            /** @description Assessment type group (e.g. Assignments, Quizzes, Exams, Labs, Projects, Reports) */
            group_name: string;
            /** Format: date-time */
            due_date?: string;
        };
        Grade: {
            id: string;
            assessment_name: string;
            score: number;
            max_score: number;
            weight: number;
            group_name: string;
            /** Format: date-time */
            graded_at: string;
            /** Format: date-time */
            submitted_at: string;
        };
        Material: {
            id: string;
            title: string;
            /** @enum {string} */
            source: "canvas" | "ed";
            /** @enum {string} */
            source_type: "module" | "lesson";
            items?: components["schemas"]["MaterialItem"][];
            slide_count?: number;
            url?: string;
        };
        MaterialItem: {
            title: string;
            type: string;
            url: string;
        };
        Discussion: {
            id: string;
            ed_thread_id: string;
            title: string;
            author: string;
            category: string;
            is_endorsed: boolean;
            is_staff_post: boolean;
            gpa_relevance_score: number;
            relevance_category: string;
            summary: string;
            /** Format: date-time */
            created_at: string;
        };
        CourseDeadline: {
            id: string;
            title: string;
            /** Format: date-time */
            due_date: string;
            source: string;
            weight?: number | null;
            /** @enum {string} */
            status: "upcoming" | "submitted" | "overdue" | "completed";
            days_remaining: number;
        };
        Deadline: components["schemas"]["CourseDeadline"] & {
            course_code: string;
            course_name: string;
            is_confirmed: boolean;
        };
        GpaReport: {
            /** @enum {string} */
            scale: "wam" | "gpa_4" | "gpa_7";
            current_wam: number;
            current_gpa_4: number;
            target_wam: number | null;
            gap: number | null;
            courses: components["schemas"]["GpaCourseSummary"][];
            /** Format: date-time */
            last_sync_at: string;
        };
        GpaCourseSummary: {
            course_id: string;
            code: string;
            name: string;
            credit_points: number;
            level_weight: number;
            current_mark: number | null;
            grade_letter: string | null;
            completed_weight: number;
        };
        GpaPrediction: {
            current_wam: number;
            predicted_wam: number;
            delta: number;
            per_course: components["schemas"]["GpaPredictionCourse"][];
        };
        GpaPredictionCourse: {
            course_id: string;
            code: string;
            current_mark: number;
            predicted_mark: number;
            applied_assumptions: components["schemas"]["WhatIfScore"][];
        };
        WhatIfScore: {
            course_id: string;
            assessment_name: string;
            assumed_score: number;
        };
        GpaPath: {
            target_wam: number;
            current_wam: number;
            is_achievable: boolean;
            per_course: components["schemas"]["GpaPathCourse"][];
        };
        GpaPathCourse: {
            course_id: string;
            code: string;
            current_mark: number;
            minimum_remaining_avg: number;
            remaining_assessments: components["schemas"]["GpaPathAssessment"][];
            /** @enum {string} */
            difficulty: "easy" | "moderate" | "hard" | "impossible";
        };
        GpaPathAssessment: {
            name: string;
            weight: number;
            minimum_score: number;
        };
        DigestLatest: {
            digest_id: string;
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            period: "daily" | "weekly";
            courses: components["schemas"]["DigestCourseEntry"][];
            urgent_deadlines: components["schemas"]["UrgentDeadline"][];
        };
        DigestCourseEntry: {
            code: string;
            highlights: components["schemas"]["DigestHighlight"][];
        };
        DigestHighlight: {
            type: string;
            summary: string;
            /** @enum {string} */
            urgency: "informational" | "important" | "critical";
            source_thread_id?: string;
        };
        UrgentDeadline: {
            course_code: string;
            title: string;
            /** Format: date-time */
            due_date: string;
            hours_remaining: number;
        };
        DigestSummary: {
            digest_id: string;
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            period: "daily" | "weekly";
            highlight_count: number;
        };
        Alert: {
            id: string;
            /** @enum {string} */
            type: "gpa_risk" | "deadline_risk" | "token_expired" | "grade_drop";
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            course_code: string;
            message: string;
            current_mark?: number;
            target_mark?: number;
            /** Format: date-time */
            deadline?: string;
            /** Format: date-time */
            created_at: string;
            is_read: boolean;
        };
        Notification: {
            id: string;
            type: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            title: string;
            body: string;
            is_read: boolean;
            action_url?: string;
            /** Format: date-time */
            created_at: string;
        };
        SyncTriggerResponse: {
            sync_id: string;
            /** @enum {string} */
            status: "in_progress" | "completed" | "failed";
            /** Format: date-time */
            started_at: string;
        };
        SyncStatusResponse: {
            last_sync: components["schemas"]["SyncDetail"];
            platforms: components["schemas"]["PlatformStatus"];
        };
        SyncDetail: {
            sync_id: string;
            /** @enum {string} */
            status: "in_progress" | "completed" | "failed";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            results: components["schemas"]["SyncResults"];
        };
        SyncResults: {
            grades?: components["schemas"]["SyncCount"];
            deadlines?: components["schemas"]["SyncCount"];
            discussions?: components["schemas"]["SyncCount"];
        };
        SyncCount: {
            synced: number;
            new: number;
            updated: number;
        };
        PlatformStatus: {
            canvas: components["schemas"]["PlatformHealth"];
            ed: components["schemas"]["PlatformHealth"];
        };
        PlatformHealth: {
            /** @enum {string} */
            status: "healthy" | "degraded" | "error";
            /** Format: date-time */
            last_success: string;
        };
        SearchResult: {
            /** @enum {string} */
            type: "material" | "discussion";
            title: string;
            source: string;
            course_code: string;
            snippet: string;
            url: string;
            relevance: number;
        };
        HealthCheck: {
            /** @enum {string} */
            status: "healthy" | "degraded";
            version: string;
            checks: {
                /** @enum {string} */
                database: "ok" | "error";
                /** @enum {string} */
                canvas_api: "ok" | "error";
                /** @enum {string} */
                ed_api: "ok" | "error";
                /** @enum {string} */
                cognito: "ok" | "error";
            };
            /** Format: date-time */
            timestamp: string;
        };
        CourseOutline: {
            course_id: string;
            /** Format: uri */
            outline_url?: string | null;
            assessments: components["schemas"]["OutlineAssessment"][];
            learning_outcomes: string[];
            /** Format: date-time */
            fetched_at: string;
            /** @enum {string} */
            source: "unit_outline" | "canvas_fallback";
        };
        OutlineAssessment: {
            name: string;
            weight: number;
            description: string;
            due_date?: string;
            length?: string;
            ai_policy?: string;
        };
        TimetableSession: {
            id: string;
            course_code: string;
            course_name: string;
            type: string;
            section: string;
            /** @description 0=Mon, 1=Tue, ..., 6=Sun */
            day: number;
            /** @description Decimal hour, e.g. 9, 14.5 */
            start_hour: number;
            end_hour: number;
            location: string;
            /** @description Teaching weeks this session runs */
            weeks: number[];
        };
        SemesterWeek: {
            /** @description 1-14 slider position */
            position: number;
            /** @description 0=break, 1-13=teaching week */
            teaching_week: number;
            label: string;
            /** Format: date */
            monday_date: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        AuthError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    display_name: string;
                };
            };
        };
        responses: {
            /** @description Registration successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user_id: string;
                            pending_verification: boolean;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            access_token: string;
                            refresh_token: string;
                            /** @description Token TTL in seconds */
                            expires_in: number;
                            user: components["schemas"]["User"];
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            access_token: string;
                            refresh_token: string;
                            expires_in: number;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Reset code sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            message: string;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
        };
    };
    confirmPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    code: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password reset successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            message: string;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    deleteCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthError"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name?: string;
                    gpa_target?: number;
                    /** @enum {string} */
                    gpa_scale?: "wam" | "gpa_4" | "gpa_7";
                };
            };
        };
        responses: {
            /** @description Updated user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    configurePlatformToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "canvas" | "ed";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Token configured and verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @enum {string} */
                            status: "active" | "invalid";
                            courses_found: number;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    removePlatformToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "canvas" | "ed";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthError"];
        };
    };
    verifyPlatformToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: "canvas" | "ed";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @enum {string} */
                            status: "active" | "invalid";
                            valid: boolean;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    exportUserData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download URL for exported data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: uri */
                            download_url: string;
                            /** Format: date-time */
                            expires_at: string;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    listCourses: {
        parameters: {
            query?: {
                /** @example 2026-S1 */
                semester?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Course"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getCourseDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseDetail"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getCourseGrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grade list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Grade"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getCourseMaterials: {
        parameters: {
            query?: {
                /** @description Filter by source platform */
                source?: "canvas" | "ed";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Material list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Material"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getCourseDiscussions: {
        parameters: {
            query?: {
                filter?: "high_value" | "endorsed" | "staff" | "all";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discussion list with pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Discussion"][];
                        meta: components["schemas"]["ResponseMeta"];
                        pagination?: components["schemas"]["CursorPagination"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getCourseDeadlines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course deadline list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseDeadline"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getCourseOutline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course outline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseOutline"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getGpaReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GPA report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GpaReport"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    predictGpa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    what_if_scores: components["schemas"]["WhatIfScore"][];
                    /** @enum {string} */
                    scale: "wam" | "gpa_4" | "gpa_7";
                };
            };
        };
        responses: {
            /** @description GPA prediction result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GpaPrediction"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    calculateGpaPath: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_wam: number;
                };
            };
        };
        responses: {
            /** @description GPA path result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GpaPath"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    listDeadlines: {
        parameters: {
            query?: {
                /** @description Start date (default today) */
                from?: string;
                /** @description End date (default semester end) */
                to?: string;
                /** @description Filter by course */
                course_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deadline list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Deadline"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getUpcomingDeadlines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upcoming deadline list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Deadline"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getLatestDigest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest digest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DigestLatest"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getDigestHistory: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Digest history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DigestSummary"][];
                        meta: components["schemas"]["ResponseMeta"];
                        pagination?: components["schemas"]["CursorPagination"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Alert"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getNotifications: {
        parameters: {
            query?: {
                unread_only?: boolean;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Notification"][];
                        meta: components["schemas"]["ResponseMeta"];
                        pagination?: components["schemas"]["CursorPagination"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    triggerSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    scope: "all" | "grades" | "deadlines" | "materials" | "discussions" | "outline";
                };
            };
        };
        responses: {
            /** @description Sync started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SyncTriggerResponse"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SyncStatusResponse"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search query string */
                q: string;
                scope?: "materials" | "discussions" | "all";
                course_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SearchResult"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["HealthCheck"];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
        };
    };
    getTimetableSessions: {
        parameters: {
            query?: {
                /** @description Teaching week number (1-13) to filter sessions */
                week?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timetable sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TimetableSession"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["AuthError"];
        };
    };
    getSemesterWeeks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Semester week structure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SemesterWeek"][];
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
}
